import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "http://localhost:3000/graphql",
  generates: {
    "./src/types/gql.ts": {
      plugins: [
        "typescript",
        "typescript-resolvers",
        {
          add: {
            content: [
              "/* eslint-disable */",
              "/**",
              "Code generated by graphql-codegen. DO NOT EDIT.",
              "Source: ./src/schema.ts",
              "Generated by this command:",
              "",
              "  npm run graphql:generate-types",
              "",
              "*/"
            ].join("\n")
          }
        },
      ],
    },
  },
};

export default config;
